### PR TITLE
Get the original destination port #2 Solved for TCP

### PR DESCRIPTION
**Pull request by MohammadBilalArif**
I have tested this code for tcp connections, it works. UDP testing is remaining. After completing for UDP I will get application layer protocol name with help of getProtocol function.

### CODE REVIEW

**Comment by glaslos** [comment]
Your PR breaks the tests: https://travis-ci.org/mushorg/glutton/builds/152418567

**Comment by glaslos** [comment]
Still failing: https://travis-ci.org/mushorg/glutton/builds/152510469
Please run the test locally before submitting a pull request.

**Comment by glaslos** [comment]
Please use sensible commit messages which describe to content and purpose of your code commit.

**Comment by MohammadBilalArif** [comment]
Sorry :( test was not working locally. I will commit after improving my code and fixing issues. 
Next time I will take care of commit messages.

**Pull request closed without merging**
